"""adding table with seed

Revision ID: 23516636a4bd
Revises: d8bc163b5a34
Create Date: 2021-07-13 15:56:03.978516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23516636a4bd'
down_revision = 'd8bc163b5a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time_frame', sa.String(), nullable=False),
    sa.Column('key_word_1', sa.String(), nullable=False),
    sa.Column('key_word_2', sa.String(), nullable=False),
    sa.Column('trend_kw_1', sa.String(), nullable=False),
    sa.Column('trend_kw_2', sa.String(), nullable=False),
    sa.Column('winner', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trends')
    # ### end Alembic commands ###
